server.port=8087
spring.application.name=comment-service
spring.datasource.url=jdbc:mysql://localhost:3306/codesync_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=${JWT_SECRET:CodeSyncSecretKey2026VeryLongSecretKeyForJWTSigning123456789}
jwt.expiration=86400000
logging.level.com.codesync=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
info.app.name=comment-service
info.app.description=Code Comments, Reviews
info.app.port=8087

# Inter-Service Communication
notification.service.url=http://localhost:8088
